theme             : jekyll-theme-minimal

favicon           : /assets/favicon.jpg
title             : "Sanghwan Lee"
logo              : /assets/lssang0000.gif

description       : "#Devops #MSA #FinTech </br>#Java #Spring #Spring-boot </br>#Container #Docker #Kubernetes  </br>#Cloud #AWS #Azure </br>#CICD #Bash #Jenkins #Git #SVN #Gradle"

url               : "https://lssang0000.github.io"
source_url        : "https://github.com/lssang0000"
baseurl           : /

github.is_blog_page    : true
github.blog_url        : "https://github.com/lssang0000/blog"
github.is_project_page : true
github.repository_url  : "https://github.com/lssang0000/lssang0000.github.io"