theme                  : jekyll-theme-minimal

title                    : "Imreplay blog"
title_separator          : "-" 
name                     : "lssasng0000" 
description              : "lssasng0000's portfolio." 
url                      : "https://lssasng0000.github.io" 