theme             : jekyll-theme-minimal

favicon           : assets/built/images/favicon.jpg
title             : "Portfolio"
title_separator   : "-" 
name              : "lssasng0000" 
description       : "#Devops #MSA #FinTech </br>#Spring #Spring-boot </br>#Container #Docker #Kubernetes  #Cloud #AWS #Azure </br>"
url               : "https://lssang0000.github.io"
source_url        : "https://github.com/lssang0000"
