theme             : jekyll-theme-minimal

favicon           : /assets/favicon.jpg
title             : "Sanghwan Lee"
logo              : /assets/lssang0000.gif

description       : "#Devops #MSA #FinTech </br>#Java #Spring #Spring-boot </br>#Container #Docker #Kubernetes  </br>#Cloud #AWS #Azure </br>#CICD #Bash #Jenkins #Git #SVN #Gradle"

url               : "https://lssang0000.github.io"
source_url        : "https://github.com/lssang0000"
baseurl           : /

repository_url    : "https://github.com/lssang0000/lssang0000.github.io"
repository_label  : "View the Project on GitHub"
repository_nwo    : "Custom of jekyll-theme-minimal"

blog_url          : "https://lssang0000.github.io/blog/"
blog_label        : "View the Blog on GitHub Page"
blog_nwo          : "Dev & Travel notes"