theme             : jekyll-theme-minimal

favicon           : assets/built/images/favicon.jpg
title             : "Portfolio - SANG HWAN LEE"
title_separator   : "-" 
name              : "lssasng0000" 
description       : "#Devops #Spring #Spring-boot #Container #Docker #Kubernetes #MSA #fin-tech #Cloud #AWS #Azure"
url               : "https://lssang0000.github.io"
source_url        : "https://github.com/lssang0000"
